# Replace the text below to customize your site
site_name: Anna Fedele - MDEF & Fab Lab Barcelona
site_description: Master in Design for Emergent Futures
site_author: Anna Fedele
copyright: Copyleft 2023 "Anna Fedele" - GNU Free Documentation License
repo_name: 'Anna : Github Repo'
site_url: https://annafedele/mdef-template/
repo_url: 'https://annafedele/fablabbcn/mdef-template'


nav:
  - Home: index.md
  - About: about/me.md
  - Master project:
      - Masteer Thesis: project/project.md
      - My Design Space: project/01-My Design Space.md
  - Reflections :
      - Term 1:
          - Landing: term1/landing/gitclass.md
          - Documenting Design: term1/01-Documenting Design.md
          - AoWS: term1/02-Atlas of Weak Signals.md
          - Design Studio 01: term1/03-Design Studio 01.md
          - The Machine Paradox: term1/04-The Machine Paradox.md
          - Living with your own ideas: term1/05-Living with your own ideas.md
          - Bio & Agri Zero: term1/06-Bio & Agri Zero.md
          - Design with Others: term1/07-Design with Others.md
          - Extended Intelligences: term1/08-Extended Intelligences.md
      - Term 2:
          - Design Studio 02: term2/01-Design Studio 02.md
          - Designing in a State of Climate Emergency: term2/02-Designing in a State of Climate Emergency.md
          - Digital Prototyping For Design: term2/03-Digital Prototyping For Design.md
          - Future Talks: term2/Future Talks.md
          - Communicating Ideas: term2/04-Communicating Ideas.md
          - Designing with Collective Intelligence: term2/05-Designing with Collective Intelligence.md
          - Measuring the world: term2/06-Measuring the world.md
          - Micro Challenges: term2/Micro Challenges.md
          - Designing with Extended Intelligences: term2/07-Designing with Extended Intelligences.md
          - Research Trip: term2/Research Trip.md
      - Term 3:
        - AOWS2: term3/01-AOWS2.md
        - Design Ethics: term3/02-Design Ethics.md  
        - Digital Prototyping: term3/03-Digital Prototyping.md




extra:
  social:
    # For other social icons at https://squidfunk.github.io/mkdocs-material/setup/adding-social-links/

    - icon: fontawesome/brands/instagram
      link: https://www.instagram.com/_whatisannadoing/
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/anna-fedele/


theme:
  name: material
  palette:
    scheme: mypalette
    # try other colors https://squidfunk.github.io/mkdocs-material/getting-started/#primary-colors
    primary: red
    accent: deep purple
  font:
    # See available fonts at https://fonts.google.com/
     text: DM Mono
     code: DM Mono

  logo: images/MT01/Risorsa4LOGOWB.png
  favicon: images/MT01/Risorsa4LOGOWB.png
  features:
    - instant
    - navigation.expand
    - navigation.indexes
    - navigation.instant
    # - navigation.prune
    # - navigation.sections
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
    - content.code.copy
plugins:
  - search
  - git-revision-date-localized:
      fallback_to_build_date: true

markdown_extensions:
  - extra
  - smarty
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - codehilite:
      guess_lang: false
  - toc:
      permalink: true
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true

  - md_in_html
  - admonition
  - codehilite
  - footnotes
  - toc:
      permalink: true
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.snippets:
      base_path: 'docs'
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  - attr_list
  - pymdownx.tabbed

extra_css:
  - stylesheets/extra.css
  - https://unpkg.com/material-components-web@latest/dist/material-components-web.min.css
